"""Rich Messages page -- Discord Components V2 webhook composer."""

import json
import os
import time

import dash
from dash import html, callback, Input, Output, State, no_update
import dash_mantine_components as dmc

from dash_widgetbot.webhook import send_webhook_message
from dash_widgetbot.components import (
    action_row,
    button,
    components_v2_message,
    container,
    media_gallery,
    section,
    separator,
    string_select,
    select_option,
    text_display,
    thumbnail,
    unfurl_media,
)

dash.register_page(
    __name__, path="/rich-messages", title="Rich Messages", name="Rich Messages"
)

WEBHOOK_URL_DEFAULT = os.getenv("DISCORD_WEBHOOK_URL", "")

# ---------------------------------------------------------------------------
# Pre-built message templates
# ---------------------------------------------------------------------------

# NOTE: Regular webhooks (created in Discord server settings) cannot send
# interactive components (buttons with custom_id, selects).  Only link-style
# buttons (with url) work.  Application-owned webhooks (created by a bot)
# support all interactive components.

TEMPLATES = {
    "welcome": lambda: components_v2_message(
        container(
            text_display("# Welcome to the Server!"),
            separator(),
            section(
                thumbnail(unfurl_media("https://cdn.discordapp.com/embed/avatars/0.png")),
                text_display(
                    "Thanks for joining! Check out the channels and say hello."
                ),
            ),
            action_row(
                button("Read the Rules", url="https://discord.com/guidelines", style="link"),
                button("Visit Website", url="https://example.com", style="link"),
            ),
            color=0x5865F2,
        ),
    ),
    "alert": lambda: components_v2_message(
        container(
            text_display("## Maintenance Alert"),
            separator(),
            text_display(
                "The server will undergo scheduled maintenance.\n\n"
                "**When:** Today at 10:00 PM UTC\n"
                "**Duration:** ~30 minutes\n"
                "**Impact:** Brief downtime expected"
            ),
            separator(spacing="large"),
            text_display("-# Please plan accordingly."),
            color=0xED4245,
        ),
    ),
    "report": lambda: components_v2_message(
        container(
            text_display("# Weekly Report Card"),
            separator(),
            section(
                thumbnail(unfurl_media("https://cdn.discordapp.com/embed/avatars/3.png")),
                text_display(
                    "**Messages:** 1,234\n"
                    "**Active Members:** 89\n"
                    "**New Joins:** 12"
                ),
            ),
            separator(),
            text_display("-# Generated by dash-widgetbot"),
            color=0x57F287,
        ),
    ),
    "media": lambda: components_v2_message(
        container(
            text_display("## Media Showcase"),
            media_gallery(
                {"media": unfurl_media("https://picsum.photos/seed/a/400/300"), "description": "Photo A"},
                {"media": unfurl_media("https://picsum.photos/seed/b/400/300"), "description": "Photo B"},
            ),
            separator(),
            text_display("-# Powered by Components V2"),
            color=0x5865F2,
        ),
    ),
}


# ---------------------------------------------------------------------------
# Layout
# ---------------------------------------------------------------------------

layout = dmc.Container(
    [
        dmc.Space(h="xl"),
        dmc.Title("Rich Messages (Components V2)", order=2, mb="md"),
        dmc.Text(
            "Send rich, structured messages to Discord using Components V2. "
            "Choose a template or compose a custom message with the builder below.",
            c="dimmed",
            mb="xl",
        ),
        # Template selector
        dmc.Paper(
            [
                dmc.Title("Message Templates", order=4, mb="xs"),
                dmc.Grid(
                    [
                        dmc.GridCol(
                            dmc.Select(
                                id="rm-template",
                                label="Choose Template",
                                data=[
                                    {"label": "Welcome Message", "value": "welcome"},
                                    {"label": "Maintenance Alert", "value": "alert"},
                                    {"label": "Weekly Report", "value": "report"},
                                    {"label": "Media Showcase", "value": "media"},
                                ],
                                value="welcome",
                            ),
                            span=6,
                        ),
                        dmc.GridCol(
                            dmc.TextInput(
                                id="rm-webhook-url",
                                label="Webhook URL",
                                placeholder="https://discord.com/api/webhooks/...",
                                value=WEBHOOK_URL_DEFAULT,
                            ),
                            span=6,
                        ),
                    ],
                    mb="md",
                ),
                dmc.Grid(
                    [
                        dmc.GridCol(
                            dmc.TextInput(
                                id="rm-username",
                                label="Username (optional)",
                                placeholder="Bot display name",
                            ),
                            span=6,
                        ),
                        dmc.GridCol(
                            dmc.TextInput(
                                id="rm-avatar-url",
                                label="Avatar URL (optional)",
                                placeholder="https://...",
                            ),
                            span=6,
                        ),
                    ],
                    mb="md",
                ),
                dmc.Group(
                    [
                        dmc.Button(
                            "Send Template", id="rm-send-btn", color="green"
                        ),
                        dmc.Button(
                            "Preview JSON", id="rm-preview-btn", variant="outline"
                        ),
                        html.Div(id="rm-result-badge"),
                    ]
                ),
            ],
            p="lg",
            withBorder=True,
            mb="md",
        ),
        # Custom message composer
        dmc.Paper(
            [
                dmc.Title("Custom Composer", order=4, mb="xs"),
                dmc.Text(
                    "Write a heading and body to send as a Components V2 container.",
                    c="dimmed",
                    size="sm",
                    mb="sm",
                ),
                dmc.TextInput(
                    id="rm-custom-heading",
                    label="Heading (markdown)",
                    placeholder="# My Heading",
                    value="# Hello from Dash!",
                    mb="sm",
                ),
                dmc.Textarea(
                    id="rm-custom-body",
                    label="Body (markdown)",
                    placeholder="Write your message content...",
                    value="This message was sent using **dash-widgetbot** Components V2 builders.",
                    minRows=3,
                    autosize=True,
                    mb="sm",
                ),
                dmc.ColorInput(
                    id="rm-custom-color",
                    label="Accent Color",
                    value="#5865F2",
                    mb="md",
                ),
                dmc.Group(
                    [
                        dmc.Button(
                            "Send Custom", id="rm-send-custom-btn", color="blue"
                        ),
                        html.Div(id="rm-custom-result-badge"),
                    ]
                ),
            ],
            p="lg",
            withBorder=True,
            mb="md",
        ),
        # JSON preview
        dmc.Paper(
            [
                dmc.Title("JSON Preview", order=4, mb="xs"),
                dmc.Code(
                    id="rm-json-preview",
                    children="Select a template and click 'Preview JSON'.",
                    block=True,
                ),
            ],
            p="lg",
            withBorder=True,
            mb="md",
        ),
        # Send history
        dmc.Paper(
            [
                dmc.Title("Send History", order=4, mb="xs"),
                html.Div(
                    id="rm-history",
                    className="event-log",
                    children="No messages sent yet.",
                ),
            ],
            p="lg",
            withBorder=True,
        ),
        dmc.Space(h="xl"),
    ],
    size="lg",
    py="xl",
)


# ---------------------------------------------------------------------------
# Callbacks
# ---------------------------------------------------------------------------


@callback(
    Output("rm-json-preview", "children"),
    Input("rm-preview-btn", "n_clicks"),
    State("rm-template", "value"),
    prevent_initial_call=True,
)
def preview_json(_n, template_key):
    if not template_key or template_key not in TEMPLATES:
        return "Select a template first."
    msg = TEMPLATES[template_key]()
    return json.dumps(msg, indent=2)


@callback(
    Output("rm-result-badge", "children"),
    Output("rm-history", "children"),
    Input("rm-send-btn", "n_clicks"),
    State("rm-template", "value"),
    State("rm-webhook-url", "value"),
    State("rm-username", "value"),
    State("rm-avatar-url", "value"),
    State("rm-history", "children"),
    prevent_initial_call=True,
)
def send_template(_n, template_key, webhook_url, username, avatar_url, history):
    if not template_key or template_key not in TEMPLATES:
        return dmc.Badge("No template selected", color="yellow"), no_update

    msg = TEMPLATES[template_key]()
    result = send_webhook_message(
        components=msg["components"],
        flags=msg.get("flags"),
        webhook_url=webhook_url or None,
        username=username or None,
        avatar_url=avatar_url or None,
    )

    if result["success"]:
        badge = dmc.Badge(f"Sent (ID: {result['message_id']})", color="green")
    else:
        badge = dmc.Badge(f"Error: {result['error'][:60]}", color="red")

    ts = time.strftime("%H:%M:%S")
    status = "OK" if result["success"] else f"ERR {result['status_code']}"
    entry = html.Div(
        f"[{ts}] {status} -- Template: {template_key}",
        className="event-log-entry",
    )

    if isinstance(history, str):
        history = []
    elif not isinstance(history, list):
        history = [history] if history else []

    return badge, [entry] + history[:49]


@callback(
    Output("rm-custom-result-badge", "children"),
    Output("rm-history", "children", allow_duplicate=True),
    Input("rm-send-custom-btn", "n_clicks"),
    State("rm-custom-heading", "value"),
    State("rm-custom-body", "value"),
    State("rm-custom-color", "value"),
    State("rm-webhook-url", "value"),
    State("rm-username", "value"),
    State("rm-avatar-url", "value"),
    State("rm-history", "children"),
    prevent_initial_call=True,
)
def send_custom(_n, heading, body, color_hex, webhook_url, username, avatar_url, history):
    # Parse hex color to int
    accent = None
    if color_hex:
        try:
            accent = int(color_hex.lstrip("#"), 16)
        except ValueError:
            pass

    children = []
    if heading:
        children.append(text_display(heading))
    children.append(separator())
    if body:
        children.append(text_display(body))

    msg = components_v2_message(container(*children, color=accent))

    result = send_webhook_message(
        components=msg["components"],
        flags=msg.get("flags"),
        webhook_url=webhook_url or None,
        username=username or None,
        avatar_url=avatar_url or None,
    )

    if result["success"]:
        badge = dmc.Badge(f"Sent (ID: {result['message_id']})", color="green")
    else:
        badge = dmc.Badge(f"Error: {result['error'][:60]}", color="red")

    ts = time.strftime("%H:%M:%S")
    status = "OK" if result["success"] else f"ERR {result['status_code']}"
    preview = (heading or "")[:40]
    entry = html.Div(
        f"[{ts}] {status} -- Custom: {preview}",
        className="event-log-entry",
    )

    if isinstance(history, str):
        history = []
    elif not isinstance(history, list):
        history = [history] if history else []

    return badge, [entry] + history[:49]
